### ISSUE TITLE
Maximum iterations reached

### ISSUE THREAD

**Issue by Jimbilben** [s-u/emdist#2]
Hi Simon,

This package is so useful! Is there a recommended size for the length of the matrix - in terms of how many location points to include? I have been getting a lot of the following warning:

In emdr(A, B, dist = dist, ...) :
  emd: Maximum number of iterations has been reached (500)

The output nevertheless makes sense and fits the numbers I put in, but of course a warning can be a bit worrying and maybe means the estimate is not accurate?

When I reduce the number of location points from 200 to 100, the warning is greatly reduced/barely occurs. Perhaps I should even reduce it further. Might an excessive number of location points cause the number of iterations to be regularly exceeded, or is there another more fundamental reason?

**Comment by s-u** [comment]
In the latest version (0.3-2) you can set the number of iterations (`max.iter`), so if it doesn't take too long try increasing it and see how the results change. The limit on iterations is there really just to make sure it doesn't run forever.

**Comment by Jimbilben** [comment]
Ah thank you - the only versions on CRAN were v3.1, but I now see in some of the files you have here that indeed there is this updated version and you can change the iterations.

A slight hitch, I've tried following some guidelines on installing packages from github, with the following code:
library(devtools)
install_github("s-u/emdist", dependencies = TRUE)

but I repeatedly get an error notification about non-zero exit status. I tried a solution of adding 'dependencies = TRUE' but that didn't seem to work. Do you have any suggestions to get the install working?

**Comment by s-u** [comment]
I wouldn't recommend devtools, did you try

```r
install.packages("emdist",repo="https://rforge.net")
```

**Comment by Jimbilben** [comment]
Unfortunately this still doesn't appear to work:

compilation terminated.
make: *** [C:/PROGRA~1/R/R-36~1.3/etc/i386/Makeconf:208: emd-r.o] Error 1
ERROR: compilation failed for package 'emdist'
* removing 'C:/Users/XXXX/Documents/R/win-library/3.6/emdist'
* restoring previous 'C:/Users/XXXX/Documents/R/win-library/3.6/emdist'
Warning in install.packages :
  installation of package ‘emdist’ had non-zero exit status

**Comment by s-u** [comment]
If you are on Windows, you need Rtools installed in order to build packages (see R documentation)

**Comment by Jimbilben** [comment]
Thanks, I have rtools installed and also reinstalled it. Unfortunately it still doesn't work. I'm also then getting an error with rtools that it seems a lot of other people have been getting https://github.com/rstudio/rstudio/issues/3563
but frankly it seems like a nightmare to sort and not really your job to solve that kind of issue! I might just have to stick with the old version and hope to not run into the iterations issue. Is there a plan to get this version of the package on cran anytime soon?

**Comment by s-u** [comment]
Assuming this is no longer relevant since 0.3-2 is on CRAN.
