### ISSUE TITLE
Result is zero despite unequal A and B

### ISSUE THREAD

**Issue by christophfriedrich** [s-u/emdist#4]
Consider the following example of two histograms that are fairly similar but not entirely:

```r
A <- c(4,5,5,5,4,1)
B <- c(4,5,5,6,4,3)
emdw(1:length(A), A, 1:length(B), B, dist="manhattan")
```

The returned result is `0`, i.e. to be interpreted as "no work required to turn A into B", despite A and B obviously not being identical. Why is this the case?

I suspected it may have to do with `sum(A)` being different from `sum(B)`, i.e. not having the same amount of dirt in the two inputs. But I tested other combinations with the same "flaw" and they gave results > 0 as expected. I tried to find documentation/papers on what exactly happens when the sums are not equal, but couldn't find detailed information on this topic besides the following, which indicates that what I'm trying to do should be possible (and comes from the homepage of Rubner himself).

> The size of the two signatures can be different. Also, the sum of weights of one signature can be different than the sum of weights of the other (partial match).
http://robotics.stanford.edu/~rubner/emd/default.htm

**Comment by s-u** [comment]
A is fully contained in B so there is no work necessary (in the parlance of the original paper, all holes can be filled with the dirt at the same location), hence the result 0 as expected. This is a quite useful property of EMD allowing its use for partial matching as noted in the quote above. The distance measure does not require that the total mass is equal, but it will only use the smaller of the two masses as holes so excess "dirt" does not influence the distance.

**Comment by christophfriedrich** [comment]
Thank you for clarifying this! So as this is the intended behaviour, I will close this issue. At first I was about to say that I don't get how this is supposed to be 'useful' as it causes that very small histograms will always have 0 distance to big ones, regardless of shape etc., e.g. `A <- c(1,1,1,1,1)` and `B <- c(3,6,9,6,3)`, but then realised that this can be taken care of by normalising them: `A/sum(A)`, `B/sum(B)`.

One reason why I was confused is that e.g. `emdL1` from the [`earthmovdist` package](https://rdrr.io/rforge/earthmovdist/) gives non-zero results even for these examples. It seems to assume that holes in the smaller histogram need to be filled with dirt from an imaginary source added on the right-hand side, penalising a difference more the further left it occurs. As this introduces a bias/skew, I'll go for the normalising approach rather than using that package.

**Comment by s-u** [comment]
Thanks for the link - I was not aware of that paper. I'll look at it in a quiet minute to see if we could fall back to the Emd-L1 algorithm for the special cases where it applies - if it can be shown that is has the same result, but is faster.
